[package]
name = "shuttle-simple-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-openai = "0.21.0"
axum = "0.7.4"
serde = { version = "1.0.202", features = ["derive"] }
shuttle-axum = "0.45.0"
shuttle-runtime = "0.45.0"
tokio = "1.28.2"
